CREATE DATABASE InLock_Games_Manha;

USE INLOCK_GAMES_MANHA;

CREATE TABLE ESTUDIOS(
ESTUDIOID INT IDENTITY PRIMARY KEY
, NOMEESTUDIO VARCHAR(250) NOT NULL
);

CREATE TABLE JOGOS(
JOGOID INT IDENTITY PRIMARY KEY
, NOMEJOGO VARCHAR(250) NOT NULL
, DESCRICAO VARCHAR(250) 
, DATALANCAMENTO DATE NOT NULL
, VALOR MONEY NOT NULL
, ESTUDIOID INT NOT NULL
FOREIGN KEY(ESTUDIOID) REFERENCES ESTUDIOS(ESTUDIOID)
);


CREATE TABLE USUARIOS(
USUARIOID INT IDENTITY PRIMARY KEY
, EMAIL VARCHAR(250) NOT NULL
, SENHA VARCHAR(250) NOT NULL
, TIPOUSUARIO VARCHAR(250) NOT NULL
);






