CREATE DATABASE SPMEDGROUP

USE SPMEDGROUP

CREATE TABLE CLINICA (
ID INT IDENTITY PRIMARY KEY
, CNPJ INT UNIQUE NOT NULL
, ENDERECO VARCHAR(250) NOT NULL
, DATA_INICIO DATE NOT NULL
, RAZAO_SOCIAL VARCHAR(250) NOT NULL
, NOME_FANTASIA VARCHAR(250)
, HORARIO_FUNCIONAMENTO DATETIME NOT NULL
, ID_MEDICO INT FOREIGN KEY REFERENCES TIPO_MEDICO(ID)
);

CREATE TABLE AREA_CLINICA (
ID INT IDENTITY PRIMARY KEY
, ESPECIALIDADE VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE STATUS_CONSULTA (
ID INT IDENTITY PRIMARY KEY
, STATUS VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE TIPO_USUARIOS (
ID INT IDENTITY PRIMARY KEY
, TIPO VARCHAR(250) UNIQUE NOT NULL
);

CREATE TABLE USUARIOS (
ID INT IDENTITY PRIMARY KEY
, NOME VARCHAR(250) NOT NULL
, CPF INT UNIQUE NOT NULL
, RG INT UNIQUE NOT NULL
, TELEFONE_CONTATO INT NOT NULL
, EMAIL VARCHAR(250) UNIQUE NOT NULL
, SENHA VARCHAR(250) NOT NULL
, ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPO_USUARIOS(ID)
, DATA_NASCIMENTO DATE NOT NULL
);

ALTER TABLE USUARIOS ADD ENDERECO VARCHAR(250) NOT NULL
SELECT * FROM USUARIOS
ALTER TABLE USUARIOS ALTER COLUMN TELEFONE_CONTATO VARCHAR(250)
ALTER TABLE USUARIOS ALTER COLUMN CPF VARCHAR(250)  NOT NULL
ALTER TABLE USUARIOS ALTER COLUMN RG VARCHAR(250)  NOT NULL


CREATE TABLE TIPO_MEDICO (
ID INT IDENTITY PRIMARY KEY
, CRM INT UNIQUE NOT NULL
, ID_AREA_CLINICA INT FOREIGN KEY REFERENCES AREA_CLINICA(ID)
, ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID)
);

ALTER TABLE TIPO_MEDICO ALTER COLUMN CRM VARCHAR(250) NOT NULL

CREATE TABLE PRONTUARIO_PACIENTE(
ID INT IDENTITY PRIMARY KEY
, NOME VARCHAR(250) NOT NULL
, ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID)
, NOTAS VARCHAR(250)
, DOENCAS VARCHAR(250)
, REMEDIOS VARCHAR(250)
);

ALTER TABLE PRONTUARIO_PACIENTE DROP COLUMN NOME;

CREATE TABLE CONSULTA (
ID INT IDENTITY PRIMARY KEY
, ID_STATUS_CONSULTA INT FOREIGN KEY REFERENCES STATUS_CONSULTA(ID)
, DATA_AGENDAMENTO DATETIME NOT NULL
, ID_MEDICO INT FOREIGN KEY REFERENCES TIPO_MEDICO(ID)
, ID_PACIENTE INT FOREIGN KEY REFERENCES PRONTUARIO_PACIENTE(ID)
, DESCRICAO VARCHAR(250)
);



