// <auto-generated />
using System;
using InLock.CodeFirst.WebApi.Manha.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InLock.CodeFirst.WebApi.Manha.Migrations
{
    [DbContext(typeof(InLockContext))]
    [Migration("20190228124601_Criacao-Banco")]
    partial class CriacaoBanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InLock.CodeFirst.WebApi.Manha.Domains.EstudioDomain", b =>
                {
                    b.Property<int>("EstudioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeEstudio")
                        .IsRequired()
                        .HasColumnName("NomeEstudio")
                        .HasColumnType("varchar(250)");

                    b.HasKey("EstudioId");

                    b.ToTable("Estudios");
                });

            modelBuilder.Entity("InLock.CodeFirst.WebApi.Manha.Domains.JogoDomain", b =>
                {
                    b.Property<int>("JogoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataLancamento");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("Text");

                    b.Property<int>("EstudioId");

                    b.Property<string>("NomeJogo")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<decimal>("Valor");

                    b.HasKey("JogoId");

                    b.HasIndex("EstudioId");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("InLock.CodeFirst.WebApi.Manha.Domains.JogoDomain", b =>
                {
                    b.HasOne("InLock.CodeFirst.WebApi.Manha.Domains.EstudioDomain", "Estudio")
                        .WithMany("Jogos")
                        .HasForeignKey("EstudioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
